### ISSUE TITLE
unable to load click.ogg

### ISSUE THREAD

**Issue by jturner65** [Tanner/Oregon-Trail#111]
i've tried refreshing, and i have the click.ogg file in resources/sounds but it doesn't seem to want to load - i get a trapped slick exception during the load screen, and then a red java exception. : Unable to load: resources/sounds/click.ogg

here's the entire stacktrace : java.io.IOException: Unable to load: resources/sounds/click.ogg
    at org.newdawn.slick.openal.SoundStore.getOgg(SoundStore.java:846)
    at org.newdawn.slick.openal.SoundStore.getOgg(SoundStore.java:793)
    at org.newdawn.slick.openal.DeferredSound.load(DeferredSound.java:90)
    at scene.LoadingScene.update(LoadingScene.java:75)
    at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:268)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:657)
    at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:408)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
    at core.GameDirector.start(GameDirector.java:75)
    at core.GameDirector.main(GameDirector.java:324)

**Comment by jturner65** [comment]
also, can we say javadox?  i knews we could.  trying to go through this code to see what could possibly be the issue.  'tis obtuse and arcane, sirs.

**Comment by Tanner** [comment]
I don't get that error, but I do get this right after click.ogg is next in line to be loaded.

Wed Nov 09 08:21:24 EST 2011 ERROR:Failure reading in vorbis
Wed Nov 09 08:21:24 EST 2011 ERROR:null
java.lang.IndexOutOfBoundsException
    at java.io.BufferedInputStream.read(BufferedInputStream.java:310)
    at org.newdawn.slick.openal.OggInputStream.getPageAndPacket(OggInputStream.java:154)
    at org.newdawn.slick.openal.OggInputStream.readPCM(OggInputStream.java:294)
    at org.newdawn.slick.openal.OggInputStream.read(OggInputStream.java:446)
    at org.newdawn.slick.openal.OggDecoder.getData(OggDecoder.java:315)
    at org.newdawn.slick.openal.SoundStore.getOgg(SoundStore.java:835)
    at org.newdawn.slick.openal.SoundStore.getOgg(SoundStore.java:793)
    at org.newdawn.slick.openal.DeferredSound.load(DeferredSound.java:90)
    at scene.LoadingScene.update(LoadingScene.java:76)
    at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:268)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:657)
    at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:408)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
    at core.GameDirector.start(GameDirector.java:75)
    at core.GameDirector.main(GameDirector.java:324)

**Comment by Irdakuh** [comment]
Weird...I'll see what's going on.  Probably my fault from trying to fix click last night

**Comment by jturner65** [comment]
this looks to be addressed
