### ISSUE TITLE
Out of bounds in PartyCreationScene

### ISSUE THREAD

**Issue by ryanashcraft** [Tanner/Oregon-Trail#20]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
    at java.util.ArrayList.RangeCheck(ArrayList.java:547)
    at java.util.ArrayList.get(ArrayList.java:322)
    at scene.PartyCreationScene$ButtonListener.personChangeProfButton(PartyCreationScene.java:394)
    at scene.PartyCreationScene$ButtonListener.componentActivated(PartyCreationScene.java:493)
    at org.newdawn.slick.gui.AbstractComponent.notifyListeners(AbstractComponent.java:82)
    at component.Button.mouseReleased(Button.java:130)
    at org.newdawn.slick.Input.poll(Input.java:1230)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:635)
    at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:408)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
    at core.GameDirector.start(GameDirector.java:55)
    at core.GameDirector.main(GameDirector.java:166)

**Comment by ryanashcraft** [comment]
Fixed in commit f9b504687ad7d47e35af0f6d79a01b1dbe19a5e0.
