### ISSUE TITLE
NullPointerException in PIS

### ISSUE THREAD

**Issue by tgrenbergj** [Tanner/Oregon-Trail#43]
Go to Store, go to PIS, put nothing in bin, press sell.

**Comment by Tanner** [comment]
I can't confirm a fix because of #45. I don't think my scene is throwing the error, but posting a stack trace would be useful.

**Comment by Irdakuh** [comment]
Stack trace:
Exception in thread "main" java.lang.NullPointerException
    at model.Inventory.getNumberOf(Inventory.java:173)
    at scene.PartyInventoryScene.getItemsInBin(PartyInventoryScene.java:320)
    at scene.PartyInventoryScene$ButtonListener.componentActivated(PartyInventoryScene.java:359)
    at org.newdawn.slick.gui.AbstractComponent.notifyListeners(AbstractComponent.java:82)
    at component.Button.mouseReleased(Button.java:135)
    at org.newdawn.slick.Input.poll(Input.java:1230)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:635)
    at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:408)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
    at core.GameDirector.start(GameDirector.java:63)
    at core.GameDirector.main(GameDirector.java:248)

Looks like you just need to check if the bin is empty before you start working with it.
